# Description: A dictionary of letters and their corresponding 5x5 matrices of True and False values. The True values
# are replaced with a snake emoji and the False values are replaced with a star emoji. The print_word function takes
# a string as an argument and prints the corresponding emoji matrix for each letter in the string.
letter_size = 5

alphabet_dict = {
    'A': [[False, False, True, False, False],
          [False, True, False, True, False],
          [True, True, True, True, True],
          [True, False, False, False, True],
          [True, False, False, False, True]],
    'B': [[True, True, True, True, False],
          [True, False, False, False, True],
          [True, True, True, True, False],
          [True, False, False, False, True],
          [True, True, True, True, False]],
    'C': [[False, True, True, True, True],
          [True, False, False, False, False],
          [True, False, False, False, False],
          [True, False, False, False, False],
          [False, True, True, True, True]],
    'D': [[True, True, True, True, False],
          [True, False, False, False, True],
          [True, False, False, False, True],
          [True, False, False, False, True],
          [True, True, True, True, False]],
    'E': [[True, True, True, True, True],
          [True, False, False, False, False],
          [True, True, True, False, False],
          [True, False, False, False, False],
          [True, True, True, True, True]],
    'F': [[True, True, True, True, True],
          [True, False, False, False, False],
          [True, True, True, False, False],
          [True, False, False, False, False],
          [True, False, False, False, False]],
    'G': [[False, True, True, True, True],
          [True, False, False, False, False],
          [True, False, True, True, True],
          [True, False, False, False, True],
          [False, True, True, True, True]],
    'H': [[True, False, False, False, True],
          [True, False, False, False, True],
          [True, True, True, True, True],
          [True, False, False, False, True],
          [True, False, False, False, True]],
    'I': [[True, True, True, True, True],
          [False, False, True, False, False],
          [False, False, True, False, False],
          [False, False, True, False, False],
          [True, True, True, True, True]],
    'J': [[False, False, False, False, True],
          [False, False, False, False, True],
          [False, False, False, False, True],
          [True, False, False, False, True],
          [False, True, True, True, False]],
    'K': [[True, False, False, True, True],
          [True, False, True, False, False],
          [True, True, False, False, False],
          [True, False, True, False, False],
          [True, False, False, True, True]],
    'L': [[True, False, False, False, False],
          [True, False, False, False, False],
          [True, False, False, False, False],
          [True, False, False, False, False],
          [True, True, True, True, True]],
    'M': [[True, False, False, False, True],
          [True, True, False, True, True],
          [True, False, True, False, True],
          [True, False, False, False, True],
          [True, False, False, False, True]],
    'N': [[True, False, False, False, True],
          [True, True, False, False, True],
          [True, False, True, False, True],
          [True, False, False, True, True],
          [True, False, False, False, True]],
    'O': [[False, True, True, True, False],
          [True, False, False, False, True],
          [True, False, False, False, True],
          [True, False, False, False, True],
          [False, True, True, True, False]],
    'P': [[True, True, True, True, False],
          [True, False, False, False, True],
          [True, True, True, True, False],
          [True, False, False, False, False],
          [True, False, False, False, False]],
    'Q': [[False, True, True, True, False],
          [True, False, False, False, True],
          [True, False, False, False, True],
          [True, False, True, False, True],
          [False, True, True, True, True]],
    'R': [[True, True, True, True, False],
          [True, False, False, False, True],
          [True, True, True, True, False],
          [True, False, True, False, True],
          [True, False, False, True, True]],
    'S': [[False, True, True, True, True],
          [True, False, False, False, False],
          [False, True, True, True, False],
          [False, False, False, False, True],
          [True, True, True, True, False]],
    'T': [[True, True, True, True, True],
          [False, False, True, False, False],
          [False, False, True, False, False],
          [False, False, True, False, False],
          [False, False, True, False, False]],
    'U': [[True, False, False, False, True],
          [True, False, False, False, True],
          [True, False, False, False, True],
          [True, False, False, False, True],
          [False, True, True, True, False]],
    'V': [[True, False, False, False, True],
          [True, False, False, False, True],
          [True, False, False, False, True],
          [False, True, False, True, False],
          [False, False, True, False, False]],
    'W': [[True, False, False, False, True],
          [True, False, False, False, True],
          [True, False, True, False, True],
          [True, True, False, True, True],
          [True, False, False, False, True]],
    'X': [[True, False, False, False, True],
          [False, True, False, True, False],
          [False, False, True, False, False],
          [False, True, False, True, False],
          [True, False, False, False, True]],
    'Y': [[True, False, False, False, True],
          [False, True, False, True, False],
          [False, False, True, False, False],
          [False, False, True, False, False],
          [False, False, True, False, False]],
    'Z': [[True, True, True, True, True],
          [False, False, False, True, False],
          [False, False, True, False, False],
          [False, True, False, False, False],
          [True, True, True, True, True]]
}

